### ISSUE TITLE
microsoft/aspnetcore-build:2.0 old versions NodeJS/npm issue when pointing to private repo.

### ISSUE THREAD

**Issue by blgrnboy** [aspnet/aspnet-docker#345] opened 2017-12-21 17:02 UTC
If you are having an issue with microsoft/aspnet, please open an issue on https://github.com/Microsoft/aspnet-docker.
This repository is for microsoft/aspnetcore and microsoft/aspnetcore-build.

## Steps to reproduce the issue
```
FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY *.sln ./
COPY WebApplication1/WebApplication1.csproj WebApplication1/
RUN dotnet restore -s https://myprivaterepohost/artifactory/api/nuget/_usbank-nuget-virtual1
COPY . .
WORKDIR /src/WebApplication1
RUN npm --version
RUN npm config set registry https://myprivaterepohost/artifactory/api/npm/npm
RUN npm config set strict-ssl false
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WebApplication1.dll"]
```
## Expected behavior
Successful image build from a machine that cannot directly connect to the internet, and uses Nuget and NPM private repos hosted on the internal network via Artifactory.

## Actual behavior
``` 
------ Initial installation of npm packages for Angular CLI ------
  node --version
  v6.11.3
  npm --version
  3.10.10
  npm install --only=production
  npm ERR! Linux 3.10.0-693.5.2.el7.x86_64
  npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--only=production"
  npm ERR! node v6.11.3
  npm ERR! npm  v3.10.10
  npm ERR! code E404

  npm ERR! 404 Not Found: artifactory
  npm ERR! 404
  npm ERR! 404  'artifactory' is not in the npm registry.
  npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
  npm ERR! 404 It was specified as a dependency of 'web-application1'
  npm ERR! 404
  npm ERR! 404 Note that you can also install from a
  npm ERR! 404 tarball, folder, http url, or git url.

  npm ERR! Please include the following file with any support request:
  npm ERR!     /src/WebApplication1/npm-debug.log
/root/.nuget/packages/afomindotcom.aspnetcore.angularcli/1.0.5/build/AfominDotCom.AspNetCore.AngularCLI.targets(12,5): error MSB3073: The command "npm install --only=production" exited with code 1. [/src/WebApplication1/WebApplication1.csproj]

Build FAILED.
```
## Additional information (e.g. issue happens only occasionally)
It seems that older versions of NPM improperly parse the registry URL, at least according to an .  NPM thinks that it should installed the package "Artifactory", but actually, that's part of the path for the registry.

When running `npm install --only=production` on my own workstation, where I have the latest version of NodeJS and npm installed, and pointing to my private repo, I do not face this issue.

## Output of `dotnet --info`

```
.NET Command Line Tools (2.1.3)

Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```

## Output of `docker info`

```
Containers: 26
 Running: 24
 Paused: 0
 Stopped: 2
Images: 75
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.5.2.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.686GiB
Name: vmaksa69901csv
ID: YCH7:EDX6:QT5V:N44I:QEYN:EJK4:UXL3:2ETP:CXIA:FQUP:O5DH:KSBF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://myprivaterepo/
Live Restore Enabled: false

```

**Comment by natemcmaster** [comment] 2017-12-21 18:06
Duplicate of #334. Upgrading existing images from node 6 to node 8 or 9 would be a breaking change. We're looking into removing node altogether in future versions of the build image.

If you need a newer version of Node, I recommend using a multi-stage build.

**Comment by blgrnboy** [comment] 2017-12-21 18:21
@natemcmaster - I am using the multi-stage Dockerfile that VS 2017 creates, which is exactly the file that I posted with a few modifications to set the npm registry and the nuget source.

It would be useful if the out-of-the-box Dockerfile generated by VS 2017 took this into account, and perhaps provided an option to use some asp.net core build image that had a later version.

Not all developers are super familiar with Docker, and expecting everyone to learn how multi-stage builds work is an unrealistic expectation.  At a minimum, it would be nice to see some documentation on how to add something to this multi-stage Dockerfile to make it work.

Another thing to keep in mind - Some VS 2017 templates out there, such as the one I am using, have the npm install scripts running on dotnet build and/or dotnet publish, which today takes place in the `microsoft/aspnetcore-build:2.0` image.

**Comment by blgrnboy** [comment] 2017-12-21 18:24
@natemcmaster Sorry for the continuation, but wouldn't a new slightly modified image with a tag such as `2.0_npm_latest` be a good alternative?  That way, the regular `2.0` tagged image would not have to be modified, and one could simply modify the default Dockerfile generated by VS to use that `2.0_npm_latest` tag instead of the default `2.0` one?

**Comment by natemcmaster** [comment] 2017-12-21 18:31
You pretty much summed up all the things we've been talking about. VS support, the complexity (and perf) of multi-stage, templates, etc. From where I sit, I don't see an easy solution. This is a fundamental problem with Docker's ability to compose.

We're also hesitant about adding a third-dimension to the version-tagging-schema of the `aspnetcore-build` image. For a long time, we got away with `aspnetcore-build:$runtimeVersion`. Now that the latest .NET Core SDK is 2.1 and the runtime is still 2.0, we had to start tagging as `aspnetcore-build:$runtimeVersion-$sdkVersion`. Expanding this to 3 makes tag names tedious. E.g. `aspnetcore-build:2.0.3-sdk-2.1.2-node-8.9.3-jessie`.

**Comment by blgrnboy** [comment] 2017-12-21 18:38
I am glad we are on the same page.  I understand that adding this third dimension would add complexity to the management of images.  But the trade-off is the number of people does this management impacts.

If Microsoft had to manage it, it would be done by one group/organization.  If every person who ran into this issue would have to try to manage this themselves, it would be a greater overall effort, and would potentially impact many groups/organizations.

**Comment by natemcmaster** [comment] 2017-12-21 18:54
Certainly. This is an issue we've been chewing on since Node 8 became LTS in October. We're still considering our options, and talking to VS teams, VSTS, and others to make sure we consider the wide impact of this change.

**Comment by blgrnboy** [comment] 2017-12-21 19:00
Cool, I will leave you to it.  What is a good way to stay up to date on this issue?  Will this particular issue be left open so that I can check back at some frequency?

**Comment by natemcmaster** [comment] 2017-12-21 19:23
I favor closing this as a duplicate of https://github.com/aspnet/aspnet-docker/issues/334.

**Comment by natemcmaster** [comment] 2018-02-16 17:11
Closing this as wont-fix. We're not planning to upgrade the version of NodeJS in existing images due to concerns about breaking changes between NodeJS 6 and 8. However, the 2.1 nightly images currently contain NodeJS 8.9. 

See also #367 for discussion on what we should do here. See also https://github.com/aspnet/aspnet-docker/issues/334#issuecomment-366297373

**Closed by natemcmaster** 2018-02-16 17:11 UTC
