### ISSUE TITLE
aspnetcore-build:1.1.0-projectjson contains bad version of Microsoft.AspNetCore.Authentication.JwtBearer

### ISSUE THREAD

**Issue by flensrocker** [aspnet/aspnet-docker#170] opened 2016-11-22 12:15 UTC
I updated our asp.net core app to 1.1 and build it inside a docker-container based on `microsoft/aspnetcore-build:1.1.0-projectjson`.

I get the following error:
`error CS1705: Assembly 'Microsoft.AspNetCore.Authentication.JwtBearer' with identity 'Microsoft.AspNetCore.Authentication.JwtBearer, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'Microsoft.IdentityModel.Tokens, Version=5.1.0.832, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.IdentityModel.Tokens' with identity 'Microsoft.IdentityModel.Tokens, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`

`Microsoft.IdentityModel.Tokens` is not directly referenced by my project.

I can build my app with the image `microsoft/dotnet:1.1.0-sdk-projectjson`, but can't publish it because of the missing node package manager `npm`.

Any suggestions, in which direction I should research on this problem? I can try to setup a small sample repo, but maybe you already know what to do... :)

I attached my [project.json](https://github.com/aspnet/aspnet-docker/files/606256/project.json.txt), [docker-compose.build.yml](https://github.com/aspnet/aspnet-docker/files/606261/docker-compose.build.yml.txt) and the [build.sh](https://github.com/aspnet/aspnet-docker/files/606262/build.sh.txt). Let me know if you need more information.

**Comment by natemcmaster** [comment] 2016-11-22 17:01
I can confirm that the Microsoft.AspNetCore.Authentication.JwtBearer assembly inside the `microsoft/aspnetcore-build:1.1.0-projectjson` image carries and assembly reference to "Microsoft.IdentityModel.Tokens, Version=5.1.0.832". It looks like the docker image has a bad cache of packages. I'll trigger a rebuild of the image on docker hub. You'll need to re-pull the image but it should solve the issue.

**Comment by natemcmaster** [comment] 2016-11-22 17:20
Fixed in https://hub.docker.com/r/microsoft/aspnetcore-build/builds/b3vvje7kta3tsby5tloamhl/

**Closed by natemcmaster** 2016-11-22 17:20 UTC
Labels: bug

**Comment by flensrocker** [comment] 2016-11-22 18:18
I can confirm that my app builds with the new image. Thank you!
