### ISSUE TITLE
aspnet-docker-windows-images official build leg failure.

### ISSUE THREAD

**Issue by ravimeda** [aspnet/aspnet-docker#270] opened 2017-07-11 19:46 UTC
## Steps to reproduce the issue
Perform an official build.

## Expected behavior
All build legs succeed.

## Actual behavior
aspnet-docker-windows-images fails https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=855095

```
2017-07-11T19:34:43.5500330Z System.InvalidOperationException: Failed to execute powershell -NoProfile -Command .\test\test.ps1 -RootImageName microsoft -Folder 2.0
2017-07-11T19:34:43.5500330Z    at Microsoft.DotNet.ImageBuilder.ExecuteHelper.Execute(ProcessStartInfo info, Func`2 executor, Boolean isDryRun, String errorMessage, String executeMessageOverride) in C:\Microsoft.DotNet.ImageBuilder\ExecuteHelper.cs:line 69
2017-07-11T19:34:43.5500330Z    at Microsoft.DotNet.ImageBuilder.ImageBuilder.RunTests() in C:\Microsoft.DotNet.ImageBuilder\ImageBuilder.cs:line 100
2017-07-11T19:34:43.5500330Z    at Microsoft.DotNet.ImageBuilder.ImageBuilder.Build() in C:\Microsoft.DotNet.ImageBuilder\ImageBuilder.cs:line 67
2017-07-11T19:34:43.5500330Z    at Microsoft.DotNet.ImageBuilder.ImageBuilder.Main(String[] args) in C:\Microsoft.DotNet.ImageBuilder\ImageBuilder.cs:line 42
2017-07-11T19:34:43.6110535Z ##[error]Process completed with exit code 1.
```

**Comment by natemcmaster** [comment] 2017-07-11 20:41
This is caused by regression in MSBuild https://github.com/Microsoft/msbuild/issues/2273 and should only be affecting nightly builds. We're expecting a fix soon.

**Comment by natemcmaster** [comment] 2017-07-13 17:08
Should be fixed by https://github.com/dotnet/dotnet-docker-nightly/pull/362.

**Closed by natemcmaster** 2017-07-13 17:08 UTC
Labels: closed-external
