### ISSUE TITLE
Solution build

### ISSUE THREAD

**Issue by kwaazaar** [aspnet/aspnet-docker#193] opened 2017-01-27 09:02 UTC
This works for building a single project. But how do i build a whole solution? dotnet restore in the solution folder works fine, dotnet build however does not (it cannot find a project.json).

**Comment by natemcmaster** [comment] 2017-01-30 19:36
Add a 'global.json' file to your project and use the 'projects' property. https://docs.microsoft.com/en-us/dotnet/articles/core/tools/global-json

Closing as the issue is external to docker.

**Closed by natemcmaster** 2017-01-30 19:36 UTC
