### ISSUE TITLE
Microsoft.ApplicationInsights.AspNetCore.dll is missing 

### ISSUE THREAD

**Issue by ZOXEXIVO** [aspnet/aspnet-docker#286] opened 2017-08-21 09:43 UTC
Ubuntu 16.04
Used many runtimes, but result is same:

Error:
  An assembly specified in the application dependencies manifest (*****.Web.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml

**Comment by natemcmaster** [comment] 2017-08-22 17:00
> Ubuntu 16.04

We don't currently support Ubuntu 16 docker images. Can you explain in more detail what you've done to encounter this error? See https://github.com/aspnet/aspnet-docker/blob/master/.github/ISSUE_TEMPLATE

**Comment by heuristicAL** [comment] 2017-09-01 12:10
I get the same error when trying to run my app from the `microsoft/dotnet:2-runtime` docker image. The only way to make it work is to use the `microsoft/dotnet:2-sdk` docker image but this isn't the best solution for a production environment...

**Comment by heuristicAL** [comment] 2017-09-01 13:16
As mentioned by the answer on [this thread](https://stackoverflow.com/questions/45720022/missing-runtime-store-error-on-linux-with-net-core-2-0-runtime-only) I fixed this error by incorporating the following run command in my Dockerfile. Should work for anyone using the Runtime instead of the SDK:
`RUN curl https://dist.asp.net/runtimestore/2.0.0/linux-x64/aspnetcore.runtimestore.tar.gz | tar xz -C /usr/share/dotnet`

**Comment by natemcmaster** [comment] 2017-09-01 14:05
@heuristicAL You can save yourself the trouble by using `microsoft/aspnetcore:2.0.0`.

https://github.com/aspnet/aspnet-docker/blob/03260d72778f0127e954110e422fccfab081d04c/2.0/stretch/runtime/Dockerfile#L1-L12

@ZOXEXIVO I'm closing for now as I don't have enough information to resolve your issue. If you are getting this error trying to use `microsoft/dotnet:2-runtime`, then this is a duplicate of https://github.com/dotnet/dotnet-docker/issues/279

**Closed by natemcmaster** 2017-09-01 14:05 UTC
Labels: more-info-needed

**Comment by heuristicAL** [comment] 2017-09-01 14:24
@natemcmaster thanks for the tip!

**Comment by ZOXEXIVO** [comment] 2017-10-26 17:09
Workaround:  Don't use AspNetCore.All.dll and include only used packages

**Comment by natemcmaster** [comment] 2017-10-26 17:19
I thought Raspberry Pi was linux-arm32, not linux-x64. ASP.NET Core doesn't support linux-arm32 yet. https://github.com/aspnet/Universe/issues/554

**Comment by TAGC** [comment] 2017-10-30 12:05
Worked fine after I made it a self-contained app by adding `-r linux-arm`:

`dotnet publish -c Release -r linux-arm -p:SolutionDir=../.. -o /app/dist`

**Comment by jdelrue** [comment] 2017-12-14 09:17
Workaround also works for Ubuntu. Seems like you have to specify your target runtime environment:

dotnet publish -c release -o publish -r linux-x64

**Comment by icavalheiro** [comment] 2018-07-05 17:56
**"-r linux-x64"** Fixed it for me.
