### ISSUE TITLE
Different Dockerfile at hub.docker.com vs github

### ISSUE THREAD

**Issue by faultylee** [aspnet/aspnet-docker#117] opened 2015-11-25 05:27 UTC
I notice someone mentioning that the Dockerfile are slower to update at hub.docker.com, but it seems to be updated, though I still see the differences, notably the base image.
From hub.docker.com
```
FROM debian:jessie

ENV DNX_VERSION 1.0.0-rc1-final
```
From here
```
FROM mono:4.0.1

ENV DNX_VERSION 1.0.0-rc1-final
```

Both are for the same 1.0.0-rc1-final

**Comment by ahmetalpbalkan** [comment] 2015-11-25 05:30
@faultylee This appears to be duplicate of #107, there is nothing we can do about it I believe. What you effectively get is what's committed on this GitHub repo.

**Comment by faultylee** [comment] 2015-11-25 05:46
Alright, indeed it was you who mentioned that' it's slow on Docker :) As you can see. the DNX_VERSION is correct. I just took a look at the commit history, it's clearer now, the one with `debian:jessie` is for `1.0.0-rc1-final-coreclr` while the one with `mono:4.0.1` is for `1.0.0-rc1-final`, running on mono. 

According to http://docs.asp.net/en/latest/getting-started/installing-on-linux.html the default is `mono`, 
>You also have a choice to use CoreCLR or Mono. At this time the microsoft/aspnet:latest repository is based on Mono.

but the DockerFile is showing the `coreclr` version. I'm assuming `latest` would pull the `coreclr` version instead.

How should I check what's actually being pulled?

**Comment by ahmetalpbalkan** [comment] 2015-11-25 05:47
@faultylee if you actually look at the project readme, you can find out what's latest. :-)  we're using the same readme format as official Docker images.

> ![image](https://cloud.githubusercontent.com/assets/159209/11389381/f2abe774-92f4-11e5-9f58-966db4f444e4.png)

**Closed by ahmetalpbalkan** 2015-11-25 05:47 UTC

**Comment by faultylee** [comment] 2015-11-25 05:49
Alright, thanks, didn't notice that.
