### ISSUE TITLE
Docker SDK no longer available

### ISSUE THREAD

**Issue by dweggemans** [aspnet/aspnet-docker#338] opened 2017-12-04 14:53 UTC
In the `1.0-2.0` images the Docker SDK is added to the image to be able to build solutions containing `.dcproj` projects:
```
RUN curl -H 'Cache-Control: no-cache' -o /tmp/Microsoft.Docker.Sdk.tar.gz https://distaspnet.blob.core.windows.net/sdk/Microsoft.Docker.Sdk.tar.gz \
    && cd /usr/share/dotnet/sdk/${DOTNET_SDK_VERSION}/Sdks \
    && tar xf /tmp/Microsoft.Docker.Sdk.tar.gz \
    && rm /tmp/Microsoft.Docker.Sdk.tar.gz
```
In the 2.x only images this SDK is missing. I used to be able to add this manually, but it seems the SDK is no longer available at the download location. 

Please add the Docker SDK to the image, or make it available again on the download location. This is failing all my CI builds.

**Comment by natemcmaster** [comment] 2017-12-04 17:11
We don't intend to put these files into the main `microsoft/aspnetcore-build` images. They were only added to the `1.0-2.0` image as a workaround because some teams took a dependency on our images, assuming https://github.com/dotnet/cli/issues/6178 would be resolved soon. The files themselves are stub files and don't actually do anything. Until the Docker Tools for VS Team brings proper support for \*.dcproj files to CLI, my recommendation is you add these stub files to your image or keep using `1.0-2.0`. I re-enabled to the download link which was temporarily unavailable. Should be up again.

I admit this is a frustrating experience for \*.dcproj. We've been in communication with the Docker Tools for VS team about it and they are looking into a solution.

Closing as a duplicate of https://github.com/dotnet/cli/issues/6178.

**Closed by natemcmaster** 2017-12-04 17:11 UTC
Labels: closed-duplicate

**Comment by rasmus** [comment] 2017-12-21 09:06
@natemcmaster Could you please re-add the DLL to the `microsoft/aspnetcore-build` images and only remove them _after_  dotnet/cli#6178 is fixed? Yes its a workaround, but the current situation is really frustrating.

**Comment by natemcmaster** [comment] 2017-12-21 18:41
@rasmus I understand the frustration. I'm not sure introducing a stub version of Microsoft.Docker.Sdk into our images is in everyone's best interest. I'm worried introducing this now would cause more issues down the road when an official version is included in the CLI. 

For example, what would you expect from a project using Microsoft.Docker.Sdk when running _inside_ a Docker container? Should it attempt to build a Docker image? Throw an error "You can't build a Docker image from inside Docker?" Noop? I don't want to predict the future on this one because I think even the team producing Microsoft.Docker.Sdk isn't sure.

In the meantime, there are other workarounds available. You can use `microsoft/aspnetcore-build:1.0-2.0`. You could create the stub version of Microsoft.Docker.Sdk from your own Dockerfile. You could configure your \*.sln file to skip building \*.dcproj files. There might be others, but these are the ones I know others use today.

Hope that helps,
-Nate

**Comment by rasmus** [comment] 2017-12-22 05:13
@natemcmaster thanks for the understanding and clarification of the problem. I'll find a workaround that works with our pipeline.

**Comment by natemcmaster** [comment] 2018-01-17 21:52
FYI -some progress is being made on this one now. See https://github.com/dotnet/cli/pull/8416
