### ISSUE TITLE
Missing Assemblies and References Using the aspnetcore-build Image.

### ISSUE THREAD

**Issue by DanJ210** [aspnet/aspnet-docker#229] opened 2017-04-27 17:50 UTC
I'm using the tutorial at this link but I'm getting tons of errors about the dependencies not existing. 
[Aspnetcore-build Tutorial](https://store.docker.com/community/images/microsoft/aspnetcore-build)
I think what's happening is the same thing that was happening with trying to run builds on VTFS... The latest .Net Core which uses NuGet 4.0 and .csproj instead of project.json does not work with what's current. I'm getting the same type of issues.

I'm not understanding why my .csproj file can be found, docker file is in the same directory as it.
file:///c%3A/Users/djackson/testing/source/noc-pl-webapplication/Dockerfile.build
[aspnetapp.zip](https://github.com/aspnet/aspnet-docker/files/962409/aspnetapp.zip)
## Steps to reproduce the issue
(e.g. copy your Dockerfile or docker-compose.yml file here)
1. Create new project in VS2017 for an empty web application OR
use the example project provided by Microsoft.
2. Follow the tutorial exactly where the build command says no source specified.

****** I also have a dotnet core project of my own. I cannot share that project but I'm one directory back where the .sln solution file would lie in a VS2017 project. I don't get the "no source" or "no .csproj file exists". BUT No dependencies will restore or missing assemblies and references after restore completes.
1. I build the image and I do not get the "no source specified" or "no such file or directory" and dotnet restore runs.
2. When the next step happens then all my assemblies and references are not found. Telling me to run a NuGet package restore to generate this file.

## Expected behavior
Have a container that builds a .Net Core project for me.

## Actual behavior
I'm getting missing assemblies and references that were restored via dotnet restore, I can see that happening in the output window.

## Output of `dotnet --info`
Only some of the output
```
Models/ViewModels/LoginViewModel.cs(9,18): error CS0246: The type or namespace name 'Name' could not be found (are you missing a using directive or an assembly
 reference?) [/app/NOC-PL-WebApplication/NOC-PL-WebApplication.csproj]
Models/ViewModels/LoginViewModel.cs(9,25): error CS0518: Predefined type 'System.String' is not defined or imported [/app/NOC-PL-WebApplication/NOC-PL-WebAppli
cation.csproj]
/usr/share/dotnet/sdk/1.0.1/Sdks/Microsoft.NET.Sdk/build/Microsoft.NET.Sdk.targets(92,5): error : Assets file '/app/NOC-PL-WebApplication/C:/Users/djackson/tes
ting/source/noc-pl-webapplication/NOC-PL-WebApplication/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/app/NOC-PL-Web
Application/NOC-PL-WebApplication.csproj]
The command '/bin/sh -c dotnet publish --output /out/ --configuration Release' returned a non-zero code: 1
```

**Comment by muratg** [comment] 2017-06-08 21:09
@DanJ210 did you find out what was wrong? Should the docs be updated?

**Comment by natemcmaster** [comment] 2017-07-06 18:51
@DanJ210  I looked at your repo. It appears the problem is your `.dockerignore` file. The repro you send me contains this:
```dockerignore
*
!published
```
When you are building the `Dockerfile.build` file, `aspnetapp.csproj` is ignored because it matches  `*`.

The second problem is the `COPY . .` line. The repro you send included the `obj/` and `bin/` folder.  The COPY line is copying your `obj/` and `bin/` folders into the docker container. `dotnet restore` fails in the container because `obj/aspnetcore.csproj.nuget.g.props` is a generated file that includes Windows paths. These file paths are not valid inside the container. For example, it contains this:

```xml
<!-- obj/aspnetcore.csproj.nuget.g.props -->
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">C:\Users\djackson\Source\Repos\dotnet-docker-samples\aspnetapp\obj\project.assets.json</ProjectAssetsFile>

```

Before running `restore` in the image, remove the `obj` folder, or update `.dockerignore` to something like this
```
obj/
bin/
!published/
```

Closing for now as this appears to be a user-configuration bug and there is nothing actionable on our end.

**Closed by natemcmaster** 2017-07-06 18:51 UTC
