### ISSUE TITLE
dotnet exits with no information with bad arguments

### ISSUE THREAD

**Issue by KevinBurton** [aspnet/aspnet-docker#354] opened 2018-01-18 07:38 UTC
If you are having an issue with microsoft/aspnet, please open an issue on https://github.com/Microsoft/aspnet-docker.
This repository is for microsoft/aspnetcore and microsoft/aspnetcore-build.

## Steps to reproduce the issue
```
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build (then throw this image away)
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "g2AspCore.dll"]
# docker run --name aspnetapp -p 80:80 -d ng2aspcore:latest

```

When I try to run a container like
`docker run --name aspnetapp -p 80:80 -d ng2aspcore`
The container immediatly exits so I look at the logs to see why (docker logs . . . .)
I see a misleading message. From this message I start to look why the 'dotnet' command is not available, rather than the real reason that the argument was incorrect.
```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```
## Expected behavior

See an error message indicating the bad argument to the command.

## Actual behavior
```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

## Output of `dotnet --info`

```
Product Information:
 Version:            2.1.3
 Commit SHA-1 hash:  a0ca411ca5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.3/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.4
  Build    : 7f262f453d8c8479b9af91d34c013b3aa05bc1ff
```

## Output of `docker info`

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: HQVQ:4GA5:2G2K:T22Q:KN3P:AAY6:QC7Z:WFBN:VT4A:SRGB:RGSX:U3L7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 41
 System Time: 2018-01-18T07:20:10.520680184Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by natemcmaster** [comment] 2018-01-19 21:47
Looks like a duplicate of https://github.com/aspnet/aspnet-docker/issues/322 and https://github.com/dotnet/core-setup/issues/3490.

Linux file systems are case-sensitive. Can you make sure the .dll file name exactly matches `"g2AspCore.dll"`?

**Comment by natemcmaster** [comment] 2018-01-24 19:37
Closing as we need more information to help you on this issue. Not trying to be mean...we just don't have enough info about your issue. We're happy to reopen if you can provide more info that helps us identify the problem. In the meantime, feel free to continue discussion.

Thanks,
-Nate

**Closed by natemcmaster** 2018-01-24 19:37 UTC
Labels: more-info-needed
