### ISSUE TITLE
coreclr-1.0.0-beta5-11624 not work for the given example

### ISSUE THREAD

**Issue by nashasha1** [aspnet/aspnet-docker#63] opened 2015-06-04 08:08 UTC
I try to make this
http://blogs.msdn.com/b/webdev/archive/2015/01/14/running-asp-net-5-applications-in-linux-containers-with-docker.aspx
work with coreclr-1.0.0-beta5-11624.

It seems coreclr does not support kpm restore or dnu restore.

What should I do??

**Comment by ahmetalpbalkan** [comment] 2015-06-11 00:14
@nashasha1 What's the error you are getting in `dnu restore`? Can you be more specific than that in your problem report? 

Using the
* sample project here: https://github.com/aspnet/Home/tree/dev/samples/latest/HelloWeb
* and a Dockerfile we add to that project: https://github.com/aspnet/aspnet-docker/blob/9fb0f020001b8640ecdcdb4ae77d95fbb4498351/.ci/build-app-image.sh#L21-L26

it must be working. I also updated the blog post you linked to reflect the latest commands.

**Comment by vlesierse** [comment] 2015-06-12 07:30
This is mainly due to the fact that dnu restore isn't supported on CoreCLR.

https://github.com/aspnet/dnx/issues/1785

**Comment by kbaley** [comment] 2015-08-22 03:06
I'm having trouble with the beta5 and beta6 images as well. The results from running `docker build -t moo .` on HelloWorldMvc in beta6 are attached. It looks like it's the same issue, that dnu restore isn't supported. The beta4 image still works though.

Is there another way to get beta6 working in Docker?

[moo.txt | uploaded via ZenHub](https://files.zenhub.io/55d7e6ebdc8bab8b71057411)

**Comment by ahmetalpbalkan** [comment] 2015-08-22 03:08
@kbaley your error seems unrelated to this issue and seems like a network issue. Can you please make sure it works outside the container well (to make sure problem is docker image; not rest of the stack) and open a new issue? Thanks.

**Comment by kbaley** [comment] 2015-08-22 04:11
Confirmed that it's not the docker image. Ran `dnu restore` on a new Linux VM and got the same error in beta6 (but again, not beta4). I'll check with the aspnet/Home project.

**Comment by BrennanConroy** [comment] 2015-08-22 04:25
Try setting the environment variable MONO_THREADS_PER_CPU=2000 before running restore

**Comment by kbaley** [comment] 2015-08-24 00:18
@BrennanConroy Success! Setting the variable allowed `dnu restore` to complete. Also, adding it to the Dockerfile allowed me to build images for the beta6 samples both on Linux and on Windows.

Is this an issue with my set up or something that needs to be addressed in the Dockerfile?

**Comment by ahmetalpbalkan** [comment] 2015-08-24 01:45
I doubt it is an issue that needs to be addressed in the Dockerfile. You're the only one reporting this error for now.

**Comment by silvath** [comment] 2015-08-24 09:51
Hi, i am getting this same error

Enviado do meu iPhone

**Comment by kbaley** [comment] 2015-08-24 13:44
@silvath Does the MONO_THREADS_PER_CPU environment variable for for you?

What does this variable do that would solve the problem for me?

**Comment by silvath** [comment] 2015-08-24 13:48
hi, i don`t have try it with beta5 or beta6. I am still using beta4

On Mon, Aug 24, 2015 at 10:44 AM, kbaley <notifications@github.com> wrote:

> @silvath <https://github.com/silvath> Does the MONO_THREADS_PER_CPU
> environment variable for for you?
>
> What does this variable do that would solve the problem for me?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aspnet/aspnet-docker/issues/63#issuecomment-134205511>
> .
>



-- 
Thiago Henrique da Silva

**Comment by ahmetalpbalkan** [comment] 2015-09-09 23:00
Closing as it seems like MONO_THREADS_PER_CPU is solving the problem.

**Closed by ahmetalpbalkan** 2015-09-09 23:00 UTC
Labels: question
