### ISSUE TITLE
container always exits itself when it is started

### ISSUE THREAD

**Issue by chennanfei** [aspnet/aspnet-docker#61] opened 2015-05-27 09:19 UTC
I am in a trouble that the container always exits when I try to run it. My image was created based on microsoft/aspnet:1.0.0-beta4. Did I do something wrong?

```
FROM microsoft/aspnet:1.0.0-beta4

COPY . /app
WORKDIR /app

RUN ["dnu", "restore"]

EXPOSE 5004
CMD ["dnx", ".", "kestrel"]
```

```
docker build -t aspnet_face .
docker run -d -p 7080:5004 --name=aspnet_face aspnet_face:latest
```

```
root@ip-172-31-46-54:/workspace# docker run -d -p 7080:5004 --name=aspnet_face aspnet_face:latest
570290ef944c52e8b8f47211c28f2e396b1b8794b7b35c2a326ee0b7b8c87cd2
root@ip-172-31-46-54:/workspace# docker ps -a
CONTAINER ID        IMAGE                                         COMMAND              CREATED             STATUS                     PORTS                    NAMES
570290ef944c        aspnet_face:latest                            "dnx . kestrel"      4 seconds ago       Exited (0) 2 seconds ago                            aspnet_face
```

**Comment by ahmetalpbalkan** [comment] 2015-05-27 13:56
Look at docker logs for the container.

**Comment by chennanfei** [comment] 2015-05-27 15:23
the output is just a word 'Started'

**Comment by ahmetalpbalkan** [comment] 2015-05-27 15:25
Ah, this is duplicate of #58. It's been an issue for a very long time. This'll be fixed in the next release.

As a workaround you can start container with `-t -d` or can do:

    CMD sleep 999999999 | dnx . kestrel

**Comment by chennanfei** [comment] 2015-05-27 15:27
Got it. I will try. Many thanks!

**Closed** 2015-05-27 15:47 UTC
